import { StyleSheet } from "react-native";
import { theme } from "@/lib/theme";

export const screenStyles = StyleSheet.create({
  screen: { flex: 1 },
  scroll: { flex: 1 },
  scrollContent: {
    padding: 16,
    paddingBottom: theme.tabBarHeight + 24,
  },
  loader: { marginTop: 32 },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  field: { marginBottom: 16 },
  label: {
    marginBottom: 4,
    fontFamily: theme.fontFamily.medium,
    fontSize: 14,
    color: theme.black,
  },
  input: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.gray200,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontFamily: theme.fontFamily.regular,
    fontSize: 16,
    color: theme.black,
  },
  primaryBtn: {
    borderRadius: 8,
    backgroundColor: theme.primary,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryBtnText: {
    fontFamily: theme.fontFamily.bold,
    fontSize: 16,
    color: theme.white,
    textAlign: "center",
  },
  card: {
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.gray100,
    padding: 16,
    backgroundColor: theme.white,
  },
  cardTitle: {
    fontFamily: theme.fontFamily.semiBold,
    fontSize: 16,
    color: theme.black,
  },
  cardDesc: {
    fontFamily: theme.fontFamily.regular,
    fontSize: 14,
    color: theme.gray600,
    marginTop: 4,
  },
  empty: {
    textAlign: "center",
    fontFamily: theme.fontFamily.regular,
    fontSize: 14,
    color: theme.gray500,
    marginTop: 16,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: theme.tabBarHeight + 24,
  },
});

export const formStyles = StyleSheet.create({
  form: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  pageIntro: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  pageTitle: {
    fontFamily: theme.fontFamily.bold,
    fontSize: 24,
    color: theme.black,
  },
  pageSubtitle: {
    fontFamily: theme.fontFamily.regular,
    fontSize: 14,
    color: theme.gray600,
    marginTop: 4,
    lineHeight: 20,
  },
  sectionTitle: {
    fontFamily: theme.fontFamily.bold,
    fontSize: 16,
    color: theme.black,
  },
  sectionSubtitle: {
    fontFamily: theme.fontFamily.regular,
    fontSize: 13,
    color: theme.gray600,
    marginTop: 2,
  },
  field: { marginBottom: 14 },
  label: {
    fontFamily: theme.fontFamily.medium,
    fontSize: 14,
    color: theme.black,
  },
  counter: {
    fontFamily: theme.fontFamily.regular,
    fontSize: 12,
    color: theme.gray500,
  },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.gray200,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: theme.fontFamily.regular,
    fontSize: 16,
    color: theme.black,
    backgroundColor: theme.gray100,
  },
  inputDisabled: {
    opacity: 0.6,
  },
  textarea: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.gray200,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: theme.fontFamily.regular,
    fontSize: 16,
    color: theme.black,
    backgroundColor: theme.gray100,
    minHeight: 100,
  },
  pitchInput: {
    minHeight: 200,
  },
  previewBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.gray200,
    backgroundColor: theme.gray100,
    padding: 14,
    minHeight: 200,
  },
  helperText: {
    fontFamily: theme.fontFamily.regular,
    fontSize: 13,
    color: theme.gray500,
    marginTop: 6,
    lineHeight: 18,
  },
  errorText: {
    marginTop: 6,
    fontFamily: theme.fontFamily.regular,
    fontSize: 13,
    color: theme.red600,
  },
  segmentTrack: {
    flexDirection: "row",
    backgroundColor: theme.gray100,
    borderRadius: 10,
    padding: 4,
    marginBottom: 12,
  },
  segmentItem: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
  },
  segmentItemActive: {
    backgroundColor: theme.white,
    shadowColor: theme.shadow100,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  segmentItemText: {
    fontFamily: theme.fontFamily.medium,
    fontSize: 13,
    color: theme.gray600,
  },
  segmentItemTextActive: {
    color: theme.black,
  },
  outlineBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.gray200,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: theme.white,
  },
  outlineBtnText: {
    fontFamily: theme.fontFamily.semiBold,
    fontSize: 14,
    color: theme.primary,
  },
  aiStack: {
    gap: 8,
    marginBottom: 12,
  },
  submitBtn: {
    borderRadius: 14,
    backgroundColor: theme.primary,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtnText: {
    fontFamily: theme.fontFamily.bold,
    fontSize: 16,
    color: theme.white,
  },
  submitBtnDisabled: {
    opacity: 0.55,
  },
  photoCard: {
    borderRadius: 12,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: theme.gray200,
    backgroundColor: theme.gray100,
    minHeight: 160,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  photoCardText: {
    fontFamily: theme.fontFamily.semiBold,
    fontSize: 15,
    color: theme.black,
    marginTop: 8,
  },
  photoCardHint: {
    fontFamily: theme.fontFamily.regular,
    fontSize: 13,
    color: theme.gray500,
    marginTop: 4,
    textAlign: "center",
  },
  imagePreviewWrap: {
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 10,
  },
  imagePreview: {
    width: "100%",
    height: 200,
    backgroundColor: theme.gray200,
  },
  imageRemoveBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(0,0,0,0.65)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  imageRemoveText: {
    fontFamily: theme.fontFamily.semiBold,
    fontSize: 12,
    color: theme.white,
  },
  analysisCard: {
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.gray200,
    backgroundColor: theme.white,
    padding: 14,
    overflow: "hidden",
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    paddingVertical: 48,
  },
  emptyStateTitle: {
    fontFamily: theme.fontFamily.bold,
    fontSize: 20,
    color: theme.black,
    marginTop: 16,
    textAlign: "center",
  },
  emptyStateSubtitle: {
    fontFamily: theme.fontFamily.regular,
    fontSize: 14,
    color: theme.gray600,
    marginTop: 8,
    textAlign: "center",
    lineHeight: 20,
  },
});
