import { colors, fonts, spacing } from "@foundrly/shared/theme";

export const theme = {
  ...colors,
  primary: colors.primary.DEFAULT,
  primary100: colors.primary[100],
  secondary: colors.secondary,
  black: colors.black.DEFAULT,
  black100: colors.black[100],
  black200: colors.black[200],
  black300: colors.black[300],
  white: colors.white.DEFAULT,
  white100: colors.white[100],
  gray100: "#F3F4F6",
  gray200: "#E5E7EB",
  gray500: "#6B7280",
  gray600: "#4B5563",
  gray700: "#374151",
  red500: "#EF4444",
  red600: "#DC2626",
  green500: "#22C55E",
  green600: "#16A34A",
  green700: "#15803D",
  purple500: "#A855F7",
  blue500: "#3B82F6",
  categoryTag: "#BBFBFF",
  shadow100: "#000000",
  shadow200: "#4E71FF",
  shadow300: "#8DD8FF",
  headerHeight: spacing.headerHeight,
  tabBarHeight: spacing.tabBarHeight,
  fontFamily: {
    regular: "WorkSans-Regular",
    medium: "WorkSans-Medium",
    semiBold: "WorkSans-SemiBold",
    bold: "WorkSans-Bold",
    extraBold: "WorkSans-ExtraBold",
    black: "WorkSans-Black",
  },
  fontName: fonts.workSans,
} as const;

export const typography = {
  heading: {
    fontFamily: theme.fontFamily.extraBold,
    fontSize: 36,
    lineHeight: 46,
    color: theme.white,
    textTransform: "uppercase" as const,
  },
  subHeading: {
    fontFamily: theme.fontFamily.medium,
    fontSize: 20,
    lineHeight: 28,
    color: theme.white,
    textAlign: "center" as const,
  },
  text30Semibold: {
    fontFamily: theme.fontFamily.semiBold,
    fontSize: 30,
    lineHeight: 36,
  },
  text26Semibold: {
    fontFamily: theme.fontFamily.semiBold,
    fontSize: 26,
    lineHeight: 32,
    color: theme.black,
  },
  text24Black: {
    fontFamily: theme.fontFamily.black,
    fontSize: 24,
    lineHeight: 30,
    color: theme.black,
  },
  text16Medium: {
    fontFamily: theme.fontFamily.medium,
    fontSize: 16,
    lineHeight: 22,
    color: theme.black,
  },
  text14Normal: {
    fontFamily: theme.fontFamily.regular,
    fontSize: 14,
    lineHeight: 20,
    color: theme.black100,
  },
} as const;
